### ISSUE TITLE
Missing brand kit

### ISSUE THREAD

**Issue by estmcmxci** [base-org/brand-kit#17]
Check: https://github.com/base-org/brand-kit/blob/main/guide/guide.pdf
<img width="1027" alt="Screenshot 2024-06-01 at 10 50 11 AM" src="https://github.com/base-org/brand-kit/assets/81047229/4c5484c8-116e-41d6-916e-c08c2303afd3">

**Comment by wbnns** [comment]
This link has been updated and resides here: https://github.com/base-org/brand-kit/blob/main/guides/brand-guide.pdf
