### ISSUE TITLE
guide.pdf page 15/36 renders incorrectly in browser.

### ISSUE THREAD

**Issue by ivcained** [base-org/brand-kit#9]
I always download all assets locally to avoid such errors.
When surfing through the preview on github, I came across something on page 15 and I don't know if anyone has seen this abnormality yet: 

Caught my eyes when Base Blue was showing up as gray: 

![guide-issue](https://github.com/base-org/brand-kit/assets/86070833/610ac967-1198-47e7-ad3a-1350368b6e55)

This guide page [15/36] renders incorrectly in Chrome and Firefox 
> When using the githib preview of the pdf:
![image](https://github.com/base-org/brand-kit/assets/86070833/0f4cd9b1-7d89-48bc-a236-9a66ddff52af)

This was resolved by simply downloading the guide.pdf locally, quite interesting to see something like this.

**Comment by wbnns** [comment]
@ivcained 

Hi there! Thanks so much for the report! Indeed, this is not displaying correct. We'll get this updated. 👍

**Comment by wbnns** [comment]
@ivcained 

Thanks again for catching and reporting this! Opened #14 which will resolve this issue. 🙏 🤝
